---
jobs:
  - redislive
  - redis
properties:
  description: "RedisLive with postgresql to monitor Redis DBs"
  webapp:
    package: RedisLive
  redislive:
    duration: 3000
    targets:
      - server: 127.0.0.1
        port: 6379
        #password: rEd!s